edition                             = "2021"
fn_params_layout                    = "Tall"
force_explicit_abi                  = true
hard_tabs                           = false
match_arm_leading_pipes             = "Never"
match_block_trailing_comma          = true
max_width                           = 80
merge_derives                       = true
newline_style                       = "Unix"
remove_nested_parens                = true
reorder_imports                     = true
reorder_modules                     = true
short_array_element_width_threshold = 10
tab_spaces                          = 4
use_field_init_shorthand            = true
use_small_heuristics                = "Max"
use_try_shorthand                   = true
